const SET_AUTHENTICATED = "SET_AUTHENTICATED";
const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
const SET_USER = "SET_USER";
const LOADING_USER = "LOADING_USER";

const SET_ERRORS = "SET_ERRORS";
const LOADING_UI = "LOADING_UI";
const CLEAR_ERRORS = "CLEAR_ERRORS";

export {
  SET_AUTHENTICATED,
  SET_UNAUTHENTICATED,
  SET_USER,
  LOADING_USER,
  SET_ERRORS,
  LOADING_UI,
  CLEAR_ERRORS,
};
